// src/models/silero_vad/c.zig
// C API for Silero VAD - used for native library builds (.a, .so, .dylib)
// Header is auto-generated by release.py from exported functions
//
// Supports two modes:
//   - Bundled: Weights embedded at compile time (build with -Dbundled=true)
//   - Lite: Weights passed by user at runtime
//
// API contract:
//   - Bundled mode: tomoul_vad_init(NULL, 0) uses embedded weights
//   - Lite mode: tomoul_vad_init(weights_ptr, len) required

const std = @import("std");
// Import via module name - build.zig maps this to the actual model module
const SileroVAD = @import("model").SileroVAD;
const build_options = @import("build_options");

// Conditionally embed the weights based on build option
const embedded_weights: ?[]const u8 = if (build_options.embed_weights)
    @embedFile("model_weights")
else
    null;

// Global state
var vad_instance: ?SileroVAD = null;
var gpa_instance: ?std.heap.GeneralPurposeAllocator(.{}) = null;

/// Initialize the VAD model
/// In bundled mode: Pass NULL, 0 to use embedded weights
/// In lite mode: Pass weights_ptr and weights_len
/// Returns true on success, false on failure
export fn tomoul_vad_init(weights_ptr: ?[*]const u8, weights_len: usize) bool {
    if (vad_instance != null) {
        return true; // Already initialized
    }

    // Determine which weights to use
    const final_weights: []const u8 = blk: {
        if (embedded_weights) |ew| {
            // Bundled mode - use embedded weights (ignore input)
            break :blk ew;
        } else {
            // Lite mode - require user-provided weights
            if (weights_ptr == null or weights_len == 0) {
                return false; // Error: No weights provided in lite mode
            }
            break :blk weights_ptr.?[0..weights_len];
        }
    };

    // Use the general purpose allocator for native builds
    gpa_instance = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa_instance.?.allocator();

    vad_instance = SileroVAD.initFromBytes(allocator, final_weights) catch {
        return false;
    };

    return true;
}

/// Process audio samples and return voice activity probability
/// audio_ptr: Pointer to f32 audio samples (16kHz, mono)
/// samples_len: Number of samples (typically 512)
/// Returns: Probability [0.0, 1.0] or negative error code
export fn tomoul_vad_process(audio_ptr: [*]const f32, samples_len: usize) f32 {
    if (vad_instance == null or gpa_instance == null) {
        return -1.0; // Not initialized
    }

    if (samples_len == 0 or samples_len > 1536) {
        return -2.0; // Invalid sample count
    }

    const Tensor = @import("tensor").Tensor;
    const allocator = gpa_instance.?.allocator();

    // Create tensor from input
    var input_shape = [_]usize{samples_len};
    var input_tensor = Tensor.init(allocator, &input_shape) catch {
        return -3.0;
    };
    defer input_tensor.deinit();

    // Copy audio data
    @memcpy(input_tensor.data, audio_ptr[0..samples_len]);

    // Run inference
    const prob = vad_instance.?.forward(&input_tensor) catch {
        return -4.0;
    };

    return prob;
}

/// Reset the VAD state (for new audio stream)
export fn tomoul_vad_reset() void {
    if (vad_instance) |*vad| {
        vad.resetStates();
    }
}

/// Check if VAD is initialized and ready
export fn tomoul_vad_is_ready() bool {
    return vad_instance != null;
}

/// Check if this is a bundled build (weights embedded)
export fn tomoul_vad_is_bundled() bool {
    return embedded_weights != null;
}

/// Free the VAD model and release memory
export fn tomoul_vad_free() void {
    if (vad_instance) |*vad| {
        vad.deinit();
        vad_instance = null;
    }
    if (gpa_instance) |*gpa| {
        _ = gpa.deinit();
        gpa_instance = null;
    }
}

/// Get the API version
export fn tomoul_vad_version() u32 {
    return 1;
}
